#!/bin/bash - 
#======================================================
#
#          FILE: all.station.vld.sh
# 
USAGE="./all.station.vld.sh"
# 
#   DESCRIPTION:    perpare data (GEBA) for calculate
#                   R, bias, rmse, for all staions
# 
#       OPTIONS: ---
#  REQUIREMENTS: ---
#          BUGS: --- unknown
#         NOTES: ---
#        AUTHOR: |CHAO.TANG| , |chao.tang.1@gmail.com|
#  ORGANIZATION: 
#       CREATED: 09/01/17 10:32
#      REVISION: 1.0
#=====================================================
set -o nounset           # Treat unset variables as an error
. ~/Shell/functions.sh   # ctang's functions


DIR="/Users/ctang/Code/CORDEX_AFR_studies/cordex.validation/"
#=================================================== 
# data used:


#ID,StaID,year,Jan,Feb,Mar,Api,May,Jun,July,Aug,Sep,Oct,Nov,Dec
InputData_0=(\
            "" \
            "cmsaf.rsds.csv" \
            "ERA_Interim.rsds.csv" \
            "SRB.rsds.csv" \
            "NCEP-CFSR.rsds.csv" \
			"CCLM.rsds.csv" \
			"CNRM-CM5.rsds.csv" \
			"CSIRO-Mk3-6-0.rsds.csv" \
			"CanESM2.rsds.csv" \
			"EC-EARTH.rsds.csv" \
			"ERA_Interim.rsds.csv" \
			"GFDL-ESM2M.rsds.csv" \
			"HIRHAM5.rsds.csv" \
			"HadGEM2-ES.rsds.csv" \
			"IPSL-CM5A-LR.rsds.csv" \
			"IPSL-CM5A-MR.rsds.csv" \
			"MIROC5.rsds.csv" \
			"MPI-ESM-LR.rsds.csv" \
			"NorESM1-M.rsds.csv" \
			"RACMO22T.rsds.csv" \
			"RCA4.rsds.csv" \
			"REMO2009.rsds.csv" \
            )
InputData_0=("GFDL-ESM2M.rsds.csv")


# for downscaled results
InputData_0=(\
            "CNRM-CM5_CLMcom-CCLM4.rsds.csv" \
            "CNRM-CM5_RCA4.rsds.csv" \
            "CSIRO-Mk3-6-0_RCA4.rsds.csv" \
            "CanESM2_RCA4.rsds.csv" \
            "EC-EARTH_CLMcom-CCLM4.rsds.csv" \
            "EC-EARTH_DMI-HIRHAM5_v2.rsds.csv" \
            "EC-EARTH_KNMI-RACMO22T.rsds.csv" \
            "EC-EARTH_MPI-CSC-REMO2009.rsds.csv" \
            "EC-EARTH_RCA4.rsds.csv" \
            "GFDL-ESM2M_RCA4.rsds.csv" \
            "HadGEM2-ES_CLMcom-CCLM4.rsds.csv" \
            "HadGEM2-ES_KNMI-RACMO22T_v2.rsds.csv" \
            "HadGEM2-ES_RCA4.rsds.csv" \
            "IPSL-CM5A-LR_GERICS-REMO2009.rsds.csv" \
            "IPSL-CM5A-MR_RCA4.rsds.csv" \
            "MIROC5_RCA4.rsds.csv" \
            "MPI-ESM-LR_CLMcom-CCLM4.rsds.csv" \
            "MPI-ESM-LR_MPI-CSC-REMO2009.rsds.csv" \
            "MPI-ESM-LR_RCA4.rsds.csv" \
            "NorESM1-M_DMI-HIRHAM5.rsds.csv" \
            "NorESM1-M_RCA4.rsds.csv" \
            )
# file $InputData_0 added by 
# mean, station,country,NO, from file $GEBA, 
# See more in function below: enhanceSARAH2
InputData=(\
            "" \
            "cmsaf.rsds.2.csv" \
            "ERA_Interim.rsds.2.csv" \
            "SRB.rsds.2.csv" \
            "NCEP-CFSR.rsds.2.csv" \
			"CCLM.rsds.2.csv" \
			"CNRM-CM5.rsds.2.csv" \
			"CSIRO-Mk3-6-0.rsds.2.csv" \
			"CanESM2.rsds.2.csv" \
			"EC-EARTH.rsds.2.csv" \
			"ERA_Interim.rsds.2.csv" \
			"GFDL-ESM2M.rsds.2.csv" \
			"HIRHAM5.rsds.2.csv" \
			"HadGEM2-ES.rsds.2.csv" \
			"IPSL-CM5A-LR.rsds.2.csv" \
			"IPSL-CM5A-MR.rsds.2.csv" \
			"MIROC5.rsds.2.csv" \
			"MPI-ESM-LR.rsds.2.csv" \
			"NorESM1-M.rsds.2.csv" \
			"RACMO22T.rsds.2.csv" \
			"RCA4.rsds.2.csv" \
			"REMO2009.rsds.2.csv" \
            "CCLM.rsds.2.csv" \
            "HIRHAM5.rsds.2.csv" \
            "RACMO22T.rsds.2.csv" \
            "RCA4.rsds.2.csv" \
            "REMO2009.rsds.2.csv" \
            )

InputData=("GFDL-ESM2M.rsds.2.csv")

InputData=(\
            "CNRM-CM5_CLMcom-CCLM4.rsds.2.csv" \
            "CNRM-CM5_RCA4.rsds.2.csv" \
            "CSIRO-Mk3-6-0_RCA4.rsds.2.csv" \
            "CanESM2_RCA4.rsds.2.csv" \
            "EC-EARTH_CLMcom-CCLM4.rsds.2.csv" \
            "EC-EARTH_DMI-HIRHAM5_v2.rsds.2.csv" \
            "EC-EARTH_KNMI-RACMO22T.rsds.2.csv" \
            "EC-EARTH_MPI-CSC-REMO2009.rsds.2.csv" \
            "EC-EARTH_RCA4.rsds.2.csv" \
            "GFDL-ESM2M_RCA4.rsds.2.csv" \
            "HadGEM2-ES_CLMcom-CCLM4.rsds.2.csv" \
            "HadGEM2-ES_KNMI-RACMO22T_v2.rsds.2.csv" \
            "HadGEM2-ES_RCA4.rsds.2.csv" \
            "IPSL-CM5A-LR_GERICS-REMO2009.rsds.2.csv" \
            "IPSL-CM5A-MR_RCA4.rsds.2.csv" \
            "MIROC5_RCA4.rsds.2.csv" \
            "MPI-ESM-LR_CLMcom-CCLM4.rsds.2.csv" \
            "MPI-ESM-LR_MPI-CSC-REMO2009.rsds.2.csv" \
            "MPI-ESM-LR_RCA4.rsds.2.csv" \
            "NorESM1-M_DMI-HIRHAM5.rsds.2.csv" \
            "NorESM1-M_RCA4.rsds.2.csv" \
            )
GEBA="rsds.mon.GEBA.csv" # generated by validation.sh
#StaID,obsID,year,Jan,Feb,Mar,Api,May,Jun,July,Aug,Sep,Oct,Nov,Dec,mean,station,country,NO



function enhanceSARAH2
{
#echo "mean","station","country","NO" > temp
awk -F "," '{print "mean"","$16","$17","$18}' $GEBA > temp

merge.sh $1 temp > $2
}

#enhanceSARAH2 ; exit


StaInfo="cmsaf.vld.sta.mab.csv" # 44 line
#NO,MAB,NO,sta_ID,lat,lon,N_month,NO,sta_ID,lat,lon,N_month,sta_ID,altitude

#=================================================== 
# output requirements:
OutputFile=(\
            "" \
            "rsds.SARAH2.allAfrica.csv" \
            "rsds.ERA_Interim.allAfrica.csv" \
            "rsds.SRB.allAfrica.csv" \
            "rsds.NCEP-CFSR.allAfrica.csv" \
			"rsds.CCLM.allAfrica.csv" \
			"rsds.CNRM-CM5.allAfrica.csv" \
			"rsds.CSIRO-Mk3-6-0.allAfrica.csv" \
			"rsds.CanESM2.allAfrica.csv" \
			"rsds.EC-EARTH.allAfrica.csv" \
			"rsds.ERA_Interim.allAfrica.csv" \
			"rsds.GFDL-ESM2M.allAfrica.csv" \
			"rsds.HIRHAM5.allAfrica.csv" \
			"rsds.HadGEM2-ES.allAfrica.csv" \
			"rsds.IPSL-CM5A-LR.allAfrica.csv" \
			"rsds.IPSL-CM5A-MR.allAfrica.csv" \
			"rsds.MIROC5.allAfrica.csv" \
			"rsds.MPI-ESM-LR.allAfrica.csv" \
			"rsds.NorESM1-M.allAfrica.csv" \
			"rsds.RACMO22T.allAfrica.csv" \
			"rsds.RCA4.allAfrica.csv" \
			"rsds.REMO2009.allAfrica.csv" \
            )
OutputFile=( "rsds.GFDL-ESM2M.allAfrica.csv" )
# c'est le GCMs
OutputFile=(\
            "rsds.CNRM-CM5_CLMcom-CCLM4.allAfrica.csv" \
            "rsds.CNRM-CM5_RCA4.allAfrica.csv" \
            "rsds.CSIRO-Mk3-6-0_RCA4.allAfrica.csv" \
            "rsds.CanESM2_RCA4.allAfrica.csv" \
            "rsds.EC-EARTH_CLMcom-CCLM4.allAfrica.csv" \
            "rsds.EC-EARTH_DMI-HIRHAM5_v2.allAfrica.csv" \
            "rsds.EC-EARTH_KNMI-RACMO22T.allAfrica.csv" \
            "rsds.EC-EARTH_MPI-CSC-REMO2009.allAfrica.csv" \
            "rsds.EC-EARTH_RCA4.allAfrica.csv" \
            "rsds.GFDL-ESM2M_RCA4.allAfrica.csv" \
            "rsds.HadGEM2-ES_CLMcom-CCLM4.allAfrica.csv" \
            "rsds.HadGEM2-ES_KNMI-RACMO22T_v2.allAfrica.csv" \
            "rsds.HadGEM2-ES_RCA4.allAfrica.csv" \
            "rsds.IPSL-CM5A-LR_GERICS-REMO2009.allAfrica.csv" \
            "rsds.IPSL-CM5A-MR_RCA4.allAfrica.csv" \
            "rsds.MIROC5_RCA4.allAfrica.csv" \
            "rsds.MPI-ESM-LR_CLMcom-CCLM4.allAfrica.csv" \
            "rsds.MPI-ESM-LR_MPI-CSC-REMO2009.allAfrica.csv" \
            "rsds.MPI-ESM-LR_RCA4.allAfrica.csv" \
            "rsds.NorESM1-M_DMI-HIRHAM5.allAfrica.csv" \
            "rsds.NorESM1-M_RCA4.allAfrica.csv" \
            )

OutputFile_GEBA="rsds.GEBA.allAfrica.csv" \

#StaID, lat lon altitude country year, month, value


LINE=$(wc -l ${InputData_0[1]} | awk '{print $1-1}'); echo $LINE


function getdata
{
    InputFile=$1
    OutputFile=$2

    echo "#LINE StaID lat lon alt Country Year Month meanRSDS" > $OutputFile

for i in {2..424}
do

    color 7 1 "I am working on LINE: $i/424"

    StaID=$(awk -F "," 'NR=='$i'{print $1}' $GEBA)
    Country=$(awk -F "," 'NR=='$i'{print $17}' $GEBA)
    Year=$(awk -F "," 'NR=='$i'{print $3}' $InputFile)

    lon=$(awk -F "," '$4=='$StaID'{print $6}' $StaInfo)
    lat=$(awk -F "," '$4=='$StaID'{print $5}' $StaInfo)
    alt=$(awk -F "," '$4=='$StaID'{print $14}' $StaInfo)



    for mon in {1..12}
    do
        Value_mon=$(awk -F "," 'NR=='$i'{print $(3+'$mon')}' $InputFile)
        #echo -n "" $mon $Value_mon

        j=$((i-1)) # get line number as same as the $Inputfile

        echo $j,$StaID,$lat,$lon,$alt,$Country,$Year,$mon,$Value_mon >> $OutputFile
    done
    
done

}

#getdata $GEBA $OutputFile_GEBA



function selyear
{

    # which file to process

    File=$1

    echo "to fit the temporal coverage of RCMs, use only from 1989 to 2005"
    echo "and to remove the low qaulity values, rm the values > 999"

    merge.sh $OutputFile_GEBA $File > temp.temp

    space.sh temp.temp > space.temp

    awk '$7 > 1989 && $9 < 999{print $0}' space.temp > selyear.temp


    awk '{print $1","$2","$3","$4","$5","$6","$7","$8","$9}' selyear.temp > $OutputFile_GEBA.1990-2005.csv
    awk '{print $10","$11","$12","$13","$14","$15","$16","$17","$18}' selyear.temp > $File.1990-2005.csv


}


#selyear $OutputFile_SARAH2



# in this function rmseason, inputfile is $OutputFile_SARAH2.1990-2005.csv
# outputfiles are 1) $file.ymonmean.csv and 2) $file.anomaly.csv

function rmseason
{
    file=$1
    # $j,$StaID,$lat,$lon,$alt,$Country,$Year,$mon,$Value_mon 
        
    
    # get ymonmean of input file
    rm $file.ymonmean.csv
    for m in {1..12}
    do
        awk -F "," '$8 == '$m'{print $2","$7","$8","$9}' $file > ${m}.temp
        awk -F "," '{sum+=$4}END{ print '$m',sum,NR,sum/NR}' ${m}.temp >> $file.ymonmean.csv
        rm *temp
    done


    LINE=$(wc -l $file | awk '{print $1}'); echo $LINE

    # loop: line-by-line
    rm $file.anomaly.csv
    for l in $(seq -s " " 1 $LINE)
    do
        month=$(awk -F "," 'NR == '$l' {print $8}' $file)
        mean=$(awk 'NR == '$month' {print $4}' $file.ymonmean.csv)

        echo $l,$month,$mean
        awk -F "," 'NR == '$l' {print $0","$9-'$mean'}' $file >> $file.anomaly.csv

    done

}

#rmseason $GEBA.1990-2005.csv



#=================================================== 
# GEBA data is done, BEFORE calling this loop.
#for kkk in $(seq -s " " 1 19)
for kkk in 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20
do
    echo $kkk ${InputData_0[$kkk]} ${InputData[$kkk]} ${OutputFile[$kkk]}

    enhanceSARAH2 ${InputData_0[$kkk]} ${InputData[$kkk]}
    getdata ${InputData[$kkk]} ${OutputFile[$kkk]}
    selyear ${OutputFile[$kkk]} # output: *.1990-2005.csv
    rmseason ${OutputFile[$kkk]}.1990-2005.csv # output: *anomaly.csv
done
