#!/bin/bash - 
#======================================================
#
#          FILE: all.station.vld.sh
# 
USAGE="./all.station.vld.sh"
# 
#   DESCRIPTION:    perpare data (GEBA) for calculate
#                   R, bias, rmse, for all staions
# 
#       OPTIONS: ---
#  REQUIREMENTS: ---
#          BUGS: --- unknown
#         NOTES: ---
#        AUTHOR: |CHAO.TANG| , |chao.tang.1@gmail.com|
#  ORGANIZATION: 
#       CREATED: 09/01/17 10:32
#      REVISION: 1.0
#=====================================================
set -o nounset           # Treat unset variables as an error
. ~/Shell/functions.sh   # ctang's functions


DIR="/Users/ctang/Code/CORDEX_AFR_studies/cordex.validation/"
#=================================================== 
# data used:


#ID,StaID,year,Jan,Feb,Mar,Api,May,Jun,July,Aug,Sep,Oct,Nov,Dec
InputData_0=(\
            "" \
            "cmsaf.rsds.csv" \
            "ERA_Interim.rsds.csv" \
            "CCLM.rsds.csv" \
            "HIRHAM5.rsds.csv" \
            "RACMO22T.rsds.csv" \
            "RCA4.rsds.csv" \
            "REMO2009.rsds.csv" \
            )

# file $InputData_0 added by 
# mean, station,country,NO, from file $GEBA, 
# See more in function below: enhanceSARAH2
InputData=(\
            "" \
            "cmsaf.rsds.2.csv" \
            "ERA_Interim.rsds.2.csv" \
            "CCLM.rsds.2.csv" \
            "HIRHAM5.rsds.2.csv" \
            "RACMO22T.rsds.2.csv" \
            "RCA4.rsds.2.csv" \
            "REMO2009.rsds.2.csv" \
            )

GEBA="rsds.mon.GEBA.csv" # generated by validation.sh
#StaID,obsID,year,Jan,Feb,Mar,Api,May,Jun,July,Aug,Sep,Oct,Nov,Dec,mean,station,country,NO



function enhanceSARAH2
{
#echo "mean","station","country","NO" > temp
awk -F "," '{print "mean"","$16","$17","$18}' $GEBA > temp

merge.sh $1 temp > $2
}

#enhanceSARAH2 ; exit


StaInfo="cmsaf.vld.sta.mab.csv" # 44 line
#NO,MAB,NO,sta_ID,lat,lon,N_month,NO,sta_ID,lat,lon,N_month,sta_ID,altitude

#=================================================== 
# output requirements:
OutputFile=(\
            "" \
            "rsds.SARAH2.allAfrica.csv" \
            "rsds.ERA_Interim.allAfrica.csv" \
            "rsds.CCLM.allAfrica.csv" \
            "rsds.HIRHAM5.allAfrica.csv" \
            "rsds.RACMO22T.allAfrica.csv" \
            "rsds.RCA4.allAfrica.csv" \
            "rsds.REMO2009.allAfrica.csv" \
            )

OutputFile_GEBA="rsds.GEBA.allAfrica.csv" \

#StaID, lat lon altitude country year, month, value


LINE=$(wc -l ${InputData[1]} | awk '{print $1-1}'); echo $LINE


function getdata
{
    InputFile=$1
    OutputFile=$2

    echo "#LINE StaID lat lon alt Country Year Month meanRSDS" > $OutputFile

for i in {2..424}
do

    color 7 1 "I am working on LINE: $i/424"

    StaID=$(awk -F "," 'NR=='$i'{print $1}' $GEBA)
    Country=$(awk -F "," 'NR=='$i'{print $17}' $GEBA)
    Year=$(awk -F "," 'NR=='$i'{print $3}' $InputFile)

    lon=$(awk -F "," '$4=='$StaID'{print $6}' $StaInfo)
    lat=$(awk -F "," '$4=='$StaID'{print $5}' $StaInfo)
    alt=$(awk -F "," '$4=='$StaID'{print $14}' $StaInfo)



    for mon in {1..12}
    do
        Value_mon=$(awk -F "," 'NR=='$i'{print $(3+'$mon')}' $InputFile)
        #echo -n "" $mon $Value_mon

        j=$((i-1)) # get line number as same as the $Inputfile

        echo $j,$StaID,$lat,$lon,$alt,$Country,$Year,$mon,$Value_mon >> $OutputFile
    done
    
done

}

#getdata $GEBA $OutputFile_GEBA



function selyear
{

    # which file to process

    File=$1

    echo "to fit the temporal coverage of RCMs, use only from 1989 to 2005"
    echo "and to remove the low qaulity values, rm the values > 999"

    merge.sh $OutputFile_GEBA $File > temp.temp

    space.sh temp.temp > space.temp

    awk '$7 > 1989 && $9 < 999{print $0}' space.temp > selyear.temp


    awk '{print $1","$2","$3","$4","$5","$6","$7","$8","$9}' selyear.temp > $OutputFile_GEBA.1990-2005.csv
    awk '{print $10","$11","$12","$13","$14","$15","$16","$17","$18}' selyear.temp > $File.1990-2005.csv


}


#selyear $OutputFile_SARAH2



# in this function rmseason, inputfile is $OutputFile_SARAH2.1990-2005.csv
# outputfiles are 1) $file.ymonmean.csv and 2) $file.anomaly.csv

function rmseason
{
    file=$1
    # $j,$StaID,$lat,$lon,$alt,$Country,$Year,$mon,$Value_mon 
        
    
    # get ymonmean of input file
    rm $file.ymonmean.csv
    for m in {1..12}
    do
        awk -F "," '$8 == '$m'{print $2","$7","$8","$9}' $file > ${m}.temp
        awk -F "," '{sum+=$4}END{ print '$m',sum,NR,sum/NR}' ${m}.temp >> $file.ymonmean.csv
        rm *temp
    done


    LINE=$(wc -l $file | awk '{print $1}'); echo $LINE

    # loop: line-by-line
    rm $file.anomaly.csv
    for l in $(seq -s " " 1 $LINE)
    do
        month=$(awk -F "," 'NR == '$l' {print $8}' $file)
        mean=$(awk 'NR == '$month' {print $4}' $file.ymonmean.csv)

        echo $l,$month,$mean
        awk -F "," 'NR == '$l' {print $0","$9-'$mean'}' $file >> $file.anomaly.csv

    done

}

#rmseason $GEBA.1990-2005.csv



#=================================================== 
# GEBA data is done, BEFORE calling this loop.
for kkk in $(seq -s " " 1 7)
do
    echo $kkk ${InputData_0[$kkk]} ${InputData[$kkk]} ${OutputFile[$kkk]}

    enhanceSARAH2 ${InputData_0[$kkk]} ${InputData[$kkk]}
    getdata ${InputData[$kkk]} ${OutputFile[$kkk]}
    selyear ${OutputFile[$kkk]} # output: *.1990-2005.csv
    rmseason ${OutputFile[$kkk]}.1990-2005.csv # output: *anomaly.csv
done
